### ISSUE TITLE
Can you invite me as contributor ?

### ISSUE THREAD

**Issue by gonza-fl** [TomasDnlAranda/project-js#8]
Step to send the invitation:

- Settings
- Collavorators
- Manage access > add people
- Insert my github user name: gonza-fl

**Comment by TomasDnlAranda** [comment]
gon ya estas de colaborador, te agregue desde el primer dia

**Comment by gonza-fl** [comment]
@TomasDnlAranda no se por que no me aparecio para aceptar la invitacion, solo me sale que respondiste esta issue
